sudo: required
dist: trusty
language: node_js
node_js:
- '4.5'
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
  add -
- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
  main" >> /etc/apt/sources.list.d/google-chrome.list'
- sudo apt-get update -q
- sudo apt-get install -q google-chrome-stable
before_script:
- npm install
script:
- npm run test-single-run
- (npm start > /dev/null &) && (npm run protractor)
deploy:
  provider: heroku
  api_key:
    secure: K/X6KhD2LmTXjHO5iCy7E17sNz3HjilqRFZUKLLOvkEbQiWs8kOztOt9vu/OUU74SFQqcGJ5RlChfUx10hYeJc4WLiu/r63hBUDLLgBRmapmxpx9nQ/iExfIz0hgZHd9sS6Jrpsh6PM+77KSoXcQS0bN2ODIlDQiI+4NTEwn2QMpAmoZqnhVwKxMmI4DRwuxSnwjzwPcVHkzUb5ps4q3eYj8PfkISWkAu6oCbxFUCZzWGZ9Df8f7boMLWMo7du2kM07g8KKU/iSg5TjwMZZXkZvmik7Dlm9sgvY6v2OTWp8rFlJe31Dsc9H7RedSHZO/IAafIovj47J+db4zkU2Y55zRhF9p0k3MNuL6lzv+/GozlRY2VxRbbhc/mztKENobKU3RgHVtUD8hqRwHQB0iZgW7KHEgl7Ug1qHBIk7xe+o/VcEBf78Bko2DnvKAtdWJ2sj3mcUpwMhEqZzIg2Qb3Wl6NJx5hw5OpyYm35t5HjsRbLiC8lpNJ+SF1IvYcFLL+qqgv5DMDiClfOMq/9/CUfJ8wPOEUP99mClCkVm4Ap2zuPheKO+l8RxbUJeQ0ZsSRZYuyMkxeZnVu9QHRf7Y4jkNv47QlHARwhkj5x5HuUSrrfBtZs7VkCLG29j0gae2JW25StgRxMRA5iaqE6livSOyksPLA9Dz85dF0aHDKY8=
  app: ttqui
  on:
    repo: zachdicus/ttqui
